### ISSUE TITLE
Any way to use as lib for dynamic endpoints update?

### ISSUE THREAD

**Issue by shisoft** [ggrandes/jrinetd#1]
Thanks for your works on such useful software.
I am working on a project that need a feature like port forward and load balance. To make jrinetd working with my application, I have to start server by make some parameters in class `Jrinetd` to public. 
Another issue is server starts with a configuration file for endpoints. In my case, endpoints needs to be update frequently. I have no idea how to update the endpoint list dynamically. Some suggestion will be great.

**Comment by ggrandes** [comment]
Thanks.
- jrinetd was designed as standalone server in mind... change the code to do library/embedable is not a rapid/easy change (but I'll keep that in mind for a future release).

But.. If you want use jrinetd like a lib with current code, you can create a "relatively safe" box using inside a classloader. You can create a webapp that run inside Tomcat (but only one instance of jrinetd by webapp. Internally jrinetd use singletons for configs and internal references to allow reloading config without breaking active connections), exposing an API to do changes in config...
- Config is autoreloadable on file modification, the file must be in "classpath + / + arg[0]" of main.

But... Inside a container like Tomcat, you can change config file (allowing persistence after hard restarts), jrinetd will reload, reflecting changes in its memory.

**Comment by ggrandes** [comment]
However, I will remake some methods to simplify the embedded (soon).

**Comment by ggrandes** [comment]
v1.1.0, done [5db9fd3a654db27cfe6d2ed2dc3a9952569e70c0], with this you can embed (not 100% perfect) in a Tomcat with a little less effort.

``` java
final Jrinetd jrinetd = new Jrinetd(configName);
jrinetd.initLog();
jrinetd.addShutdownHook();
jrinetd.start();
// Do Things
jrinetd.stop();
```

**Comment by shisoft** [comment]
Thanks 
I have seen you make it more handy on the lifecycle of the server. I am wondering is there any to to reset or alter the redirection server lists.

**Comment by ggrandes** [comment]
I suppose that you are using Server.class directly for embed, without Jrinetd (daemon). I do a patch v1.1.1 [1f17dc1d02bf0b88c41d90cf7b61bdc99e50c7dd], with this, you can use Server().getEndPoint().setAddress("host1:port1,host2:port2,...")
