### ISSUE TITLE
failover not work

### ISSUE THREAD

**Issue by chunlinyao** [ggrandes/jrinetd#2]
This is my config file

    forward 0.0.0.0:13690 10.40.1.3:13690,10.40.1.4:13690 FAILOVER

If 10.40.1.3 is down, It keeps trying to connect 10.40.1.3.

**Comment by ggrandes** [comment]
Failover is like a "retry on fail", first try 10.40.1.3, if timeout or refused, try 10.40.1.4, is this the behavior that you can see?

**Comment by chunlinyao** [comment]
It seems failover not work without LB=RR.

**Comment by ggrandes** [comment]
Maybe you want FAILOVER,LB=ORDER

**Comment by ggrandes** [comment]
You are right, i forgot, failover is an flag-option on LB's mode.

**Comment by chunlinyao** [comment]
Is there a method to not do LB just failover, Because my backup link is slow, It only used as an backup.

**Comment by ggrandes** [comment]
Thanks for your fix [#3]
