### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [ggrandes/jrinetd#4]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/org/javastack/jrinetd/IOHelper.java: Line number => 80: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/org/javastack/jrinetd/IOHelper.java: Line number => 92: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/org/javastack/jrinetd/IOHelper.java: Line number => 93: API name => MessageDigest:<BR> File name => src/main/java/org/javastack/jrinetd/IOHelper.java: Line number => 93: API name => MessageDigest:<BR> File name => src/main/java/org/javastack/jrinetd/IOHelper.java: Line number => 81: API name => MessageDigest:<BR> File name => src/main/java/org/javastack/jrinetd/IOHelper.java: Line number => 81: API name => MessageDigest:<BR>

**Comment by ggrandes** [comment]
MD5 is used to derive a value with some dispersion (as a String.hashCode could do), but high security is not required. No bug, everything is correct. Thank you.
